---
- name: "Task 1 : gathering facts using ios_facts module"
  ios_facts:
  when: ansible_network_os == 'ios'
   
- name: "Task 2 : display certain facts"
  debug:
    msg: "The host name is {{ansible_net_hostname}} running on {{ansible_net_version}}"



